upgrade 3rdparty/ packages
findlib 1.4.1 -> 1.5.1
pcre-ocaml 7.0.4 -> 7.1.1

diff --git a/3rdparty/libs/findlib/configure b/3rdparty/libs/findlib/configure
--- a/3rdparty/libs/findlib/configure
+++ b/3rdparty/libs/findlib/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# $Id: configure 204 2014-03-02 18:05:35Z gerd $
+# $Id: configure 220 2014-06-25 10:22:58Z gerd $
 # ----------------------------------------------------------------------
 #
 
@@ -7,7 +7,7 @@
 
 #set -x
 
-version="1.4.1"
+version="1.5.1"
 
 # Remember the old IFS value:
 oldifs="$IFS"
@@ -116,6 +116,7 @@ ocaml_sitelib=""
 ocamlfind_config=""
 with_toolbox=0
 with_topfind=1
+with_camlp4=1
 custom=-custom
 system=""
 
@@ -148,6 +149,9 @@ while [ "$#" != "0" ]; do
 	-no-topfind) with_topfind=0
 	         shift
 		 ;;
+	-no-camlp4) with_camlp4=0
+	         shift
+	         ;;
 	-version)
 	         echo "$version"
 		 exit 0
@@ -161,6 +165,7 @@ while [ "$#" != "0" ]; do
 		  echo "  -system <systype>    override system type (esp. mingw and win32)" 1>&2
 		  echo "  -with-toolbox        also build the toolbox" 1>&2
 		  echo "  -no-topfind          don't install topfind script into stdlib directory" 1>&2
+		  echo "  -no-camlp4           don't install the camlp4 META file" 1>&2
 		  exit
 		  ;;
          *)       echo "configure: run 'configure -h' to get help" 1>&2
@@ -345,7 +350,7 @@ if ocamlc -config >/dev/null 2>/dev/null; then
 	ocaml_threads="vm"
     fi
 else
-    # Old ocamlc do not have -config. 
+    # Old ocamlc do not have -config.
     rm -f itest-aux/simple
     ocamlc -w a -custom -thread -o itest-aux/simple unix.cma threads.cma itest-aux/simple_threads.ml \
 	>itest-aux/err.out 2>&1
@@ -427,7 +432,10 @@ fi
 
 # Check on camlp4:
 
-if in_path camlp4; then
+if [ $with_camlp4 -eq 0 ]; then
+    lcamlp4=''
+    echo "camlp4: disabled"
+else if in_path camlp4; then
     camlp4_dir=`camlp4 -where | tr -d '\015'`
     if [ ${use_cygpath} -gt 0 ]; then
 	camlp4_dir=`echo x | env USE_CYGPATH=1 tools/patch x "$camlp4_dir"`
@@ -455,7 +463,9 @@ if in_path camlp4; then
     echo "camlp4: using $camlp4_cmd, style $camlp4style"
 else
     lcamlp4=''
-    echo "camlp4: not present"
+    with_camlp4=0
+    echo "camlp4: not present (normal since OCaml-4.02)"
+fi
 fi
 
 # compiler-libs?
@@ -477,10 +487,22 @@ else
     ldbm=""
 fi
 
+# bytes?
+
+if [ -f "${ocaml_core_stdlib}/bytes.cmi" ]; then
+    echo "bytes: found, installing fake library"
+    lbytes="bytes"
+    cbytes=0
+else
+    echo "bytes: not found, installing compat library"
+    lbytes=""
+    cbytes=1
+fi
+
 
 # Generate the META files now.
 
-l="$ldbm dynlink graphics num num-top str threads unix stdlib bigarray $llabltk $lcamlp4 $lobuild $lcomplibs"
+l="$ldbm dynlink graphics num num-top str threads unix stdlib bigarray $llabltk $lcamlp4 $lobuild $lcomplibs $lbytes"
 
 for dir in site-lib-src/*; do
     # We do not really know if $dir is a directory.
@@ -538,6 +560,9 @@ parts="findlib"
 if [ $with_toolbox -gt 0 ]; then
     parts="$parts findlib-toolbox"
 fi
+if [ $cbytes -gt 0 ]; then
+    parts="$parts bytes"
+fi
 
 echo "# Makefile.config written by configure" >Makefile.config
 echo "OCAML_CORE_STDLIB=${ocaml_core_stdlib}" >>Makefile.config
@@ -554,7 +579,9 @@ echo "EXEC_SUFFIX=${exec_suffix}" >>Makefile.config
 echo "CUSTOM=${custom}" >>Makefile.config
 echo "PARTS=${parts}" >>Makefile.config
 echo "INSTALL_TOPFIND=${with_topfind}" >>Makefile.config
+echo "INSTALL_CAMLP4=${with_camlp4}" >>Makefile.config
 echo "USE_CYGPATH=${use_cygpath}" >>Makefile.config
+echo "HAVE_NATDYNLINK=${have_natdynlink}" >>Makefile.config
 echo "VERSION=${version}" >>Makefile.config
 echo "SYSTEM=${system}" >>Makefile.config
 if [ "$mingw_lib" != "" ]; then
@@ -594,6 +621,12 @@ if [ -z "$custom" ]; then
     echo "Link custom runtime:       no"
 else
     echo "Link custom runtime:       yes"
+fi
+
+if [ $cbytes -gt 0 ]; then
+    echo "Need bytes compatibility:  yes"
+else
+    echo "Need bytes compatibility:  no"
 fi
 
 echo
